### ISSUE TITLE
Apache NiFi 0.15.3 support

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/nifi-operator#224]
**Which new version of Apache NiFi should we support?**

0.15.3

**Additional information**

At the time of writing Apache NiFi 0.15.3 is the latest version. I would like support for this version so as to include bug and security fixes added since 0.15.0.

**Changes required**

Are there any upstream changes that we need to support? **No new features**

**Implementation checklist**

Please don't change anything in this list.
Not all of these steps are necessary for all versions.

- [ ] Update the Docker image
- [ ] Update documentation to include supported version(s)
- [ ] Update operator to support the new version (if needed)
- [ ] Update integration tests to test use the new versions (in addition or replacing old versions
- [ ] Update examples to use new versions

**Comment by fhennig** [comment]
@Jimvin we've added support for 1.16.3, which is the latest version as of today. Would that be okay? 

Now that I think about it, maybe we should also support the latest patch version for 1.15? Not sure, just wanted to notify you on some progress on this ticket.

**Comment by Jimvin** [comment]
That would certainly be OK, thank you!
