### ISSUE TITLE
As a user I would like to be able to set the Java heap settings for NiFi

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/nifi-operator#231]
### Current and expected behavior

As a user I should be able to set the Java memory (and potentially other Java options) in the CRD when deploying NiFI. The Java options -Xms and -Xmx are currently hard coded in rust/operator-binary/src/config.rs and set to 1024 MB, which is too small for many use cases.

### Possible solution

Provide a document a means of updating the Java command line arguments and overriding the maximum heap size.

**Comment by soenkeliebau** [comment]
fixed in #265
