### ISSUE TITLE
Docs: Getting started guide

### ISSUE THREAD

**Issue by adwk67** [stackabletech/nifi-operator#325]
Part of this epic: https://github.com/stackabletech/documentation/issues/237

Acceptance criteria:
- [ ] a new module `getting_started` exists, with an `index.adoc`, a `installation.adoc` and `first_steps.adoc`
- [ ] The old `installation.adoc` is removed.
- [ ] All the `yaml` and shell snippets are in the `examples/code` directory and can be executed as a script, to test the documentation
- [ ] versions to install are templated using the `template_docs.sh` script and the `templating_vars.yaml` file.
- [ ] Any example files that are incorporated into the getting started guide are removed from the examples directory (because there they are not tested, with the new script they will be tested).

**Comment by lfrancke** [comment]
This mentions "nightly" everywhere. We will have to update this for the release next week.

**Comment by maltesander** [comment]
> This mentions "nightly" everywhere. We will have to update this for the release next week.

Yeah this is templated and should be changed before the release.

**Comment by lfrancke** [comment]
Great! Thank you. I put in a note into the release ticket.

**Comment by maltesander** [comment]
I put a "bump" documentation there yesterday. But probably needs more context :D
