### ISSUE TITLE
[NEW VERSION] 1.18.0

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/nifi-operator#358]
**Which new version of Apache NiFi should we support?**

1.18.0

**Additional information**

**1.18.0**

[Release Notes](https://cwiki.apache.org/confluence/display/NIFI/Release+Notes#ReleaseNotes-Version1.18.0)

- Have various values including sensitive ones like passwords and other things for your flow definitions but dont want them stored in NiFi?  Parameter Providers to the rescue!  NiFi now allows you to register parameter providers such as HashiCorp Vault,  an external database, AWS or GCP Secrets Management. We'll add others like Azure soon.
- NiFi now supports pluggable Registry Clients. This will allow for follow-on implementations such as using a plain git repository as a 'registry' for versioned flows.
- CompressContent now supports ZStd and Brotli.
- New processors to List and Fetch data using SMB.
- New processor to QueryAirtable
- New component to use Azure's Event Hub as a record sink called AzureEventHubRecordSink
- New processors to List and Fetch data from Dropbox.
- New processors to List and Fetch data from Box.
- New processor to get data from HubSpot called GetHubSpot
- New processors to capture data from Workday called GetWorkdayReport.
- New processor to pull data from Zendesk.
- Default run duration on processors is now configurable.
- We can now publish to MQTT using the record mechanism which is far more efficient and flexible.

Updated a ton of dependencies for security and behavior improvements.  Fixed a ton of bugs.  Improved clustering performance.

**1.17.0**

[Release notes](https://cwiki.apache.org/confluence/display/NIFI/Release+Notes#ReleaseNotes-Version1.17.0)

- NiFi can now be built on ARM based platforms including latest MacOS systems.
- New processor to support query of data from Salesforce.
- New ConsumeTwitter processor to replace the deprecated GetTwitter processor.
- Dynamic properties can now be marked by the user as sensitive and the framework will handle them properly.  Many components updated to take advantage of this support.
- The built in content viewer now supports image/webp.
- Added the ability to track detailed metrics such as CPU at processor level.
- New processors to List and Fetch Google Drive files.
- NiFi application, as well as ListenHTTP and HandleHttpRequest processors now support HTTP/2.
- Hundreds of other bug fixes, improvements and dependency updates for better stability and to eliminate libraries with reported vulnerabilities.

**Changes required**

Does not seem to have any breaking changes.

**Implementation checklist**

Please don't change anything in this list.
Not all of these steps are necessary for all versions.

- [x] Update the Docker image
- [x] Update documentation to include supported version(s)
- [x] Update operator to support the new version (if needed)
- [x] Update integration tests to test use the new versions (in addition or replacing old versions
- [x] Update examples to use new versions

**Comment by maltesander** [comment]
There is 1.18.0 as release candidate voting on they way: https://cwiki.apache.org/confluence/display/NIFI/Release+Notes#ReleaseNotes-Version1.18.0 . Anyone has an idea how long this takes?

**Comment by lfrancke** [comment]
Usually 72 hours

**Comment by maltesander** [comment]
1.18.0 is released, do we want to support both or just 1.18?

**Comment by lfrancke** [comment]
As far as I'm concerned only 1.18 is fine. Means to recheck the release notes. 
I can't move things around on the phone. Could you do a quick refinement again?

**Comment by maltesander** [comment]
I updated, no breaking changes from what i can tell.
