### ISSUE TITLE
Overriding "nifi.web.proxy.host" will fail the CreateReportingTask Job

### ISSUE THREAD

**Issue by maltesander** [stackabletech/nifi-operator#468]
When overriding nifi.web.proxy.host, the allowed host names set by the operator are overriden.

External access via proxy works but the ReportingTaskJob will fail due to the internal access:

The request contained an invalid host header [nifi.default.svc.cluster.local:8443] in the request [/nifi-api/access/token]. Check for request manipulation or third-party intercept.

We should offer a field in the CRD to add other proxy hosts to our existing hosts list instead of just being able to set this field via overrides and completely removing the ones set by the operator.

Quick fix for this would be to override:
nifi.web.proxy.host=myproxy,nifi.default.svc.cluster.local:8443

which only works in this case if the cluster name is nifi and deployed to the default namespace.

**Comment by idemery** [comment]
+1.
A field in the NifiCluster CRD to whitelist any headers added by the user would do.

**Comment by sbernauer** [comment]
@maltesander @Jimvin I would be in favor of closing this in favor of the more elegant solution in https://github.com/stackabletech/nifi-operator/issues/604, WDYT?

**Comment by Jimvin** [comment]
Agreed, I'm happy for this issue to be closed.

**Comment by maltesander** [comment]
Agreed, closing this.
