### ISSUE TITLE
Include Iceberg processors in NiFi image

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/nifi-operator#489]
https://issues.apache.org/jira/browse/NIFI-10442 added a `PutIceberg` processor, but it is not included by default.
IMHO there is enough value in it to include it in our images

**Comment by Jimvin** [comment]
There is a lot of value to this, I'd say this is the best processor for managing data in Iceberg tables.

**Comment by sbernauer** [comment]
In Arch meeting we talked about this and agreed to include it in our image, even when we have the code to load in arbitrary extensions in the future as Iceberg is important enough
