### ISSUE TITLE
OpenID Connect support

### ISSUE THREAD

**Issue by fhennig** [stackabletech/nifi-operator#507]
As a user I would like to be able to use OpenID Connect (OIDC) as an authentication mechanism.

[useful blog post about the topic](https://bryanbende.com/development/2017/10/03/apache-nifi-openid-connect)

**Comment by sbernauer** [comment]
The following link might help https://github.com/orgs/stackabletech/discussions/29#discussioncomment-6657116

**Comment by fhennig** [comment]
closed in favor of #519
