### ISSUE TITLE
keySecret required: How do I generate it then?

### ISSUE THREAD

**Issue by fhennig** [stackabletech/nifi-operator#538]
In this struct:

    pub struct NifiSensitivePropertiesConfig {
        pub key_secret: String,
        pub algorithm: Option<NifiSensitiveKeyAlgorithm>,
        #[serde(default)]
        pub auto_generate: bool,
    }

the key_secret is required. How can I then use the `auto_generate` feature?

**Comment by maltesander** [comment]
If the secret does not exist its generated by the operator:
https://github.com/stackabletech/nifi-operator/blob/f53b0cf5fc438c7bd377da7ea32a9996f3071968/rust/operator-binary/src/controller.rs#L1386

**Comment by fhennig** [comment]
Okay thank you, I understand. This feature should be documented in the usage guide.
